// Auto-generated by scripts/import-catalog.ts. Do not edit by hand.
// Re-generate with:  bun scripts/import-catalog.ts
//
// Install identifiers backfilled from the install catalog (first-official-method
// extraction). Only methods that map cleanly onto an existing Managers field are
// imported; hand-curated entries in curated.ts take precedence.
import type { Managers } from "./types.js";

export const catalog: Record<string, Managers> = {
  "below": {
    "dnf": "below"
  },
  "binsider": {
    "cargo": "binsider"
  },
  "bottom": {
    "cargo": "bottom"
  },
  "bpytop": {
    "pip": "bpytop"
  },
  "bullmq-dash": {
    "brew": "quanghuynt14/tap/bullmq-dash"
  },
  "cheatshh": {
    "pip": "cheatshh"
  },
  "claws": {
    "brew": "clawscli/tap/claws"
  },
  "dashbrew": {
    "go": "github.com/rasjonell/dashbrew/cmd/dashbrew"
  },
  "dolphie": {
    "pip": "dolphie"
  },
  "fubar": {
    "cargo": "fubar-cli"
  },
  "glances": {
    "pip": "cd"
  },
  "gobang": {
    "brew": "tako8ki/tap/gobang"
  },
  "gonzo": {
    "go": "github.com/control-theory/gonzo/cmd/gonzo"
  },
  "gping": {
    "brew": "gping"
  },
  "hwinfo-tui": {
    "winget": "hwinfo-tui"
  },
  "kaskade": {
    "brew": "kaskade"
  },
  "kmon": {
    "cargo": "kmon"
  },
  "psmux": {
    "winget": "psmux"
  },
  "psnet": {
    "cargo": "psnet"
  },
  "pstop": {
    "winget": "marlocarlo.pstop"
  },
  "puffin": {
    "brew": "siddhantac/puffin/puffin"
  },
  "raijin": {
    "cargo": "Raijin"
  },
  "rustnet": {
    "brew": "rustnet"
  },
  "s-tui": {
    "pip": "s-tui"
  },
  "tufw": {
    "apt": "tufw_0.1.0_linux_amd64.deb"
  },
  "updo": {
    "brew": "owloops/tap/updo"
  },
  "wander": {
    "brew": "robinovitch61/tap/wander"
  },
  "wtf": {
    "brew": "wtfutil"
  },
  "act3": {
    "brew": "dhth/tap/act3"
  },
  "amtui": {
    "brew": "pehlicd/tap/amtui"
  },
  "austin-tui": {
    "pip": "austin-tui"
  },
  "brows": {
    "brew": "rubysolo/tools/brows"
  },
  "catalyst": {
    "brew": "PraveenGongada/tap/catalyst"
  },
  "chiko": {
    "brew": "felangga/chiko/chiko"
  },
  "codex": {
    "npm": "@openai/codex"
  },
  "crush": {
    "brew": "charmbracelet/tap/crush"
  },
  "dblab": {
    "brew": "danvergara/tools/dblab"
  },
  "ddv": {
    "cargo": "ddv"
  },
  "fast-resume": {
    "brew": "angristan/tap/fast-resume"
  },
  "feluda": {
    "cargo": "feluda"
  },
  "gitui": {
    "pacman": "gitui"
  },
  "gitv": {
    "brew": "jayanaxhf/taps/gitv"
  },
  "git-crecord": {
    "pip": "./setup.py"
  },
  "git-scope": {
    "brew": "Bharath-code/tap/git-scope"
  },
  "hcom": {
    "brew": "aannoo/hcom/hcom"
  },
  "heretek": {
    "cargo": "heretek"
  },
  "hunk": {
    "npm": "hunkdiff"
  },
  "jqp": {
    "brew": "jqp"
  },
  "lazymake": {
    "brew": "lazymake"
  },
  "lazysql": {
    "brew": "lazysql"
  },
  "logradar": {
    "cargo": "."
  },
  "loglens": {
    "brew": "Caelrith/loglens/loglens"
  },
  "models": {
    "brew": "models"
  },
  "nap": {
    "go": "github.com/maaslalani/nap@main"
  },
  "pproftui": {
    "go": "github.com/Oloruntobi1/pproftui"
  },
  "prs": {
    "brew": "dhth/tap/prs"
  },
  "pyautogit": {
    "pip": "pyautogit"
  },
  "qo": {
    "brew": "kiki-ki/tap/qo"
  },
  "regex-tui": {
    "go": "github.com/vitor-mariano/regex-tui"
  },
  "resterm": {
    "brew": "resterm"
  },
  "runme": {
    "brew": "runme"
  },
  "scope": {
    "cargo": "scope-monitor"
  },
  "sabiql": {
    "brew": "riii111/sabiql/sabiql"
  },
  "stu": {
    "cargo": "stu"
  },
  "termdbms": {
    "go": "github.com/mathaou/termdbms"
  },
  "terraform-tui": {
    "brew": "idoavrah/homebrew/tftui"
  },
  "serie": {
    "cargo": "serie"
  },
  "soft-serve": {
    "brew": "charmbracelet/tap/soft-serve"
  },
  "sq": {
    "go": "github.com/sheenazien8/sq"
  },
  "dtop": {
    "brew": "dtop"
  },
  "dockly": {
    "npm": "dockly"
  },
  "dockmate": {
    "brew": "shubh-io/tap/dockmate"
  },
  "docker-dash": {
    "brew": "GustavoCaso/tap/docker-dash"
  },
  "ducker": {
    "cargo": "ducker"
  },
  "eks-node-viewer": {
    "brew": "aws/tap/eks-node-viewer"
  },
  "kdash": {
    "brew": "kdash-rs/kdash/kdash"
  },
  "kubetui": {
    "brew": "kubetui"
  },
  "lazycontainer": {
    "brew": "lazycontainer"
  },
  "lazydocker": {
    "brew": "jesseduffield/lazydocker/lazydocker"
  },
  "lazytrivy": {
    "brew": "owenrumney/tools/lazytrivy"
  },
  "oxker": {
    "cargo": "oxker"
  },
  "pocker": {
    "pip": "pocker-tui"
  },
  "sen": {
    "pip": "&&"
  },
  "swarmcli": {
    "brew": "eldara-tech/tap/swarmcli"
  },
  "durdraw": {
    "pip": "git"
  },
  "frogmouth": {
    "pip": "frogmouth"
  },
  "zee": {
    "cargo": "zee"
  },
  "adbtuifm": {
    "go": "github.com/darkhz/adbtuifm"
  },
  "deletor": {
    "go": "github.com/pashkov256/deletor"
  },
  "lf": {
    "go": "\"env"
  },
  "tuifimanager": {
    "pip": "tuifimanager"
  },
  "tui-2048": {
    "pip": "tui-2048"
  },
  "chess-tui": {
    "brew": "thomas-mauran/tap/chess-tui"
  },
  "maze": {
    "brew": "itchyny/tap/maze"
  },
  "pokete": {
    "pip": "pokete"
  },
  "typeinc": {
    "pip": "typeinc"
  },
  "typing-game-cli": {
    "npm": "typing-game-cli"
  },
  "argenta": {
    "pip": "argenta"
  },
  "py_cui": {
    "pip": "py-cui"
  },
  "python prompt toolkit": {
    "pip": "prompt_toolkit"
  },
  "urwid": {
    "pip": "urwid"
  },
  "gocui": {
    "go": "github.com/jroimartin/gocui"
  },
  "tui-go": {
    "go": "github.com/marcusolsson/tui-go"
  },
  "blessed (node.js)": {
    "npm": "blessed"
  },
  "gum": {
    "brew": "gum"
  },
  "ink": {
    "npm": "ink"
  },
  "moulti": {
    "pip": "moulti;"
  },
  "basalt": {
    "cargo": "basalt-tui"
  },
  "instagram-cli": {
    "npm": "@i7m/instagram-cli"
  },
  "mastui": {
    "pip": "mastui"
  },
  "nomadnet": {
    "pip": "nomadnet"
  },
  "nostratui": {
    "cargo": "git"
  },
  "sclack": {
    "pip": "git"
  },
  "tgt": {
    "cargo": "tgt"
  },
  "tuisky": {
    "cargo": "tuisky"
  },
  "zulip-terminal": {
    "pip": "zulip-term"
  },
  "asciimol": {
    "pip": "asciimol"
  },
  "bluetui": {
    "cargo": "bluetui"
  },
  "diary": {
    "cargo": "diary"
  },
  "digisurf": {
    "cargo": "digisurf"
  },
  "distrobox-tui": {
    "go": "github.com/phanirithvij/distrobox-tui@main"
  },
  "ec2-instance-selector": {
    "brew": "aws/tap/ec2-instance-selector"
  },
  "flawz": {
    "cargo": "flawz"
  },
  "gif-for-cli": {
    "pip": "gif-for-cli"
  },
  "godap": {
    "go": "git"
  },
  "golazo": {
    "brew": "0xjuanma/tap/golazo"
  },
  "gpg-tui": {
    "cargo": "gpg-tui"
  },
  "humble explorer": {
    "pip": "humble-explorer"
  },
  "mac-cleanup-go": {
    "brew": "mac-cleanup-go"
  },
  "neoss": {
    "npm": "neoss"
  },
  "oha": {
    "cargo": "oha"
  },
  "packemon": {
    "go": "git"
  },
  "pass-cli": {
    "brew": "reyamira/homebrew-tap/pass-cli"
  },
  "pug": {
    "go": "github.com/leg100/pug"
  },
  "physics-tui": {
    "pip": "git+https://github.com/ClaudioRMalvino/physics_tui.git"
  },
  "redu": {
    "cargo": "redu"
  },
  "rocket.term": {
    "pip": "./setup.py"
  },
  "smassh": {
    "pip": "smassh"
  },
  "systemd-manager-tui": {
    "apt": "dpkg"
  },
  "tcpterm": {
    "go": "github.com/sachaos/tcpterm"
  },
  "tab-pal": {
    "pip": "tab-pal"
  },
  "tweakcc": {
    "npm": "tweakcc"
  },
  "try-rs": {
    "cargo": "git"
  },
  "vortix": {
    "brew": "Harry-kp/tap/vortix"
  },
  "wego": {
    "go": "github.com/schachmat/wego"
  },
  "wifui": {
    "winget": "wifui"
  },
  "ani-l": {
    "cargo": "ani-l"
  },
  "asak": {
    "cargo": "asak"
  },
  "bookokrat": {
    "brew": "bookokrat"
  },
  "cmdpxl": {
    "pip": "cmdpxl"
  },
  "cmus": {
    "apt": "cmus"
  },
  "draw": {
    "go": "github.com/maaslalani/draw"
  },
  "favicon-editor": {
    "go": "github.com/xyproto/favicon-editor"
  },
  "gadacz": {
    "cargo": "git"
  },
  "image-sorter": {
    "cargo": "image-sorter"
  },
  "jellyfin-tui": {
    "cargo": "git"
  },
  "managarr": {
    "cargo": "managarr"
  },
  "manga-tui": {
    "cargo": "manga-tui"
  },
  "marstui-audio": {
    "cargo": "apt"
  },
  "mps-youtube": {
    "pip": "yewtube"
  },
  "relax-player": {
    "cargo": "relax-player"
  },
  "sonicradio": {
    "go": "github.com/dancnb/sonicradio/cmd/sonicradio"
  },
  "spotatui": {
    "brew": "LargeModGames/spotatui/spotatui"
  },
  "spotui": {
    "pip": "spotui"
  },
  "tdf": {
    "cargo": "https://github.com/itsjunetime/tdf.git"
  },
  "termusic": {
    "cargo": "termusic"
  },
  "textual-paint": {
    "pip": "pipx"
  },
  "timg": {
    "apt": "timg"
  },
  "upiano": {
    "pip": "upiano"
  },
  "wiremix": {
    "cargo": "wiremix"
  },
  "ytui-music": {
    "cargo": "git"
  },
  "viu": {
    "cargo": "git"
  },
  "brief": {
    "brew": "williamagh/tap/brief"
  },
  "calcure": {
    "pip": "calcure"
  },
  "desktop-tui": {
    "cargo": "desktop-tui"
  },
  "doxx": {
    "brew": "bgreenwell/tap/doxx"
  },
  "drako": {
    "go": "github.com/lucky7xz/drako"
  },
  "ekphos": {
    "cargo": "ekphos"
  },
  "elia": {
    "pip": "3.11"
  },
  "fjira": {
    "brew": "fjira"
  },
  "glow": {
    "brew": "glow"
  },
  "gocheat": {
    "go": "git"
  },
  "helm": {
    "brew": "0xjuanma/tap/helm"
  },
  "hnjobs": {
    "go": "github.com/mwinters0/hnjobs"
  },
  "hygg": {
    "cargo": "hygg"
  },
  "judo": {
    "cargo": "judo"
  },
  "kanban": {
    "cargo": "kanban-cli"
  },
  "kanban-python": {
    "pip": "kanban-python"
  },
  "khal": {
    "apt": "khal"
  },
  "lazyssh": {
    "brew": "Adembc/homebrew-tap/lazyssh"
  },
  "longbridge-terminal": {
    "brew": "longbridge/tap/longbridge-terminal"
  },
  "lssh": {
    "brew": "blacknon/lssh/lssh"
  },
  "mcfly": {
    "brew": "mcfly"
  },
  "multranslate": {
    "npm": "multranslate"
  },
  "nless": {
    "pip": "nothing-less"
  },
  "numr": {
    "brew": "nasedkinpv/tap/numr"
  },
  "pdiary": {
    "pip": "https://github.com/manipuladordedados/pdiary/releases/download/1.65/pdiary-1.65-py3-none-any.whl"
  },
  "pomo": {
    "brew": "bahaaio/pomo/pomo"
  },
  "procmux": {
    "pip": "procmux"
  },
  "productivity-timer": {
    "npm": "productivity-timer"
  },
  "slides": {
    "brew": "slides"
  },
  "sshm": {
    "brew": "Gu1llaum-3/sshm/sshm"
  },
  "taskline": {
    "npm": "@perryrh0dan/taskline"
  },
  "tododo": {
    "brew": "bmarse/tap/tododo"
  },
  "topydo": {
    "pip": "topydo"
  },
  "ttm": {
    "brew": "vst93/tap/ttm"
  },
  "tui_projectmanager": {
    "cargo": "project_manager"
  },
  "tuidict": {
    "cargo": "tuidict"
  },
  "tuios": {
    "brew": "tuios"
  },
  "tui-slides": {
    "cargo": "tui-slides"
  },
  "tuiserial": {
    "cargo": "tuiserial"
  },
  "visidata": {
    "pip": "visidata"
  },
  "walker": {
    "cargo": "git"
  },
  "tock": {
    "brew": "tock"
  },
  "astroterm": {
    "dnf": "astroterm"
  },
  "rxpipes": {
    "cargo": "rxpipes"
  },
  "castero": {
    "pip": "castero"
  },
  "catenavetus": {
    "pip": "python"
  },
  "cloudflare-speed-cli": {
    "cargo": "cloudflare-speed-cli"
  },
  "eilmeldung": {
    "brew": "christo-auer/eilmeldung/eilmeldung"
  },
  "haxor-news": {
    "pip": "haxor-news"
  },
  "nyaa": {
    "cargo": "nyaa"
  },
  "omaro": {
    "cargo": "omaro"
  },
  "tblogs": {
    "brew": "ezeoleaf/tap/tblogs"
  },
  "textual-web": {
    "pip": "textual-web"
  }
};
