/**
 * Generate src/registry/tools.ts from src/registry/source/list.md plus the
 * curated install map in src/registry/curated.ts.
 *
 * Run with:  bun scripts/parse-list.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { curated } from "../src/registry/curated.js";
import { catalog } from "../src/registry/catalog.js";
import type { Category, Tool } from "../src/registry/types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const sourcePath = path.join(root, "src", "registry", "source", "list.md");
const outPath = path.join(root, "src", "registry", "tools.ts");

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function normalizeName(name: string): string {
  return name.trim().toLowerCase();
}

const markdown = readFileSync(sourcePath, "utf8");
const lines = markdown.split("\n");

const categories: Category[] = [];
const tools: Tool[] = [];
const usedSlugs = new Set<string>();

let currentCategory: string | null = null;
let currentSubcategory: string | null = null;
let lastTool: Tool | null = null;

const seenCategory = new Set<string>();

function uniqueSlug(base: string): string {
  let candidate = base;
  let n = 2;
  while (usedSlugs.has(candidate)) {
    candidate = `${base}-${n}`;
    n += 1;
  }
  usedSlugs.add(candidate);
  return candidate;
}

for (const rawLine of lines) {
  const line = rawLine;

  // Category header: <details open><summary><h2>Name</h2></summary>
  const catMatch = line.match(/<details[^>]*><summary><h2>(.*?)<\/h2><\/summary>/);
  if (catMatch) {
    const name = catMatch[1]!.trim();
    const id = slug(name);
    currentCategory = id;
    currentSubcategory = null;
    lastTool = null;
    if (!seenCategory.has(id)) {
      seenCategory.add(id);
      categories.push({ id, name });
    }
    continue;
  }

  if (/^<\/details>/.test(line)) {
    currentCategory = null;
    currentSubcategory = null;
    lastTool = null;
    continue;
  }

  // Subcategory header (Libraries): <h3>Python</h3>
  const subMatch = line.match(/<h3>(.*?)<\/h3>/);
  if (subMatch) {
    currentSubcategory = subMatch[1]!.trim().toLowerCase();
    lastTool = null;
    continue;
  }

  // Tool entry: - [Name](url) description
  const entryMatch = line.match(/^- \[(.*?)\]\((.*?)\)\s*(.*)$/);
  if (entryMatch && currentCategory) {
    const name = entryMatch[1]!.trim();
    const url = entryMatch[2]!.trim();
    const description = entryMatch[3]!
      .trim()
      .replace(/\*\*/g, "")
      .replace(/\s+/g, " ")
      .trim();

    const id = uniqueSlug(slug(name));
    const binaries = currentCategory === "libraries" ? [] : [id];

    const managers = { ...catalog[normalizeName(name)], ...curated[normalizeName(name)] };

    lastTool = {
      id,
      name,
      url,
      description,
      category: currentCategory,
      subcategory: currentSubcategory ?? undefined,
      binaries,
      managers,
    };
    tools.push(lastTool);
    continue;
  }

  // Continuation line: indented text continuing the previous description.
  if (
    lastTool &&
    currentCategory &&
    /^\s{2,}\S/.test(line) &&
    !/^---/.test(line) &&
    !line.startsWith("<")
  ) {
    const extra = line.trim().replace(/\*\*/g, "").replace(/\s+/g, " ");
    if (extra) lastTool.description = `${lastTool.description} ${extra}`.trim();
  }
}

// Report curated keys that did not match any tool in the list.
const matchedNames = new Set(tools.map((t) => normalizeName(t.name)));
const unmatched = Object.keys(curated).filter((k) => !matchedNames.has(normalizeName(k)));
if (unmatched.length > 0) {
  console.warn(`\n⚠ ${unmatched.length} curated key(s) did not match any tool:`);
  console.warn("  " + unmatched.join(", "));
}

const header = `// Auto-generated by scripts/parse-list.ts. Do not edit by hand.
// Re-generate with:  bun scripts/parse-list.ts
import type { Category, Tool } from "./types.js";

`;

const body =
  `export const categories: Category[] = ${JSON.stringify(categories, null, 2)};\n\n` +
  `export const tools: Tool[] = ${JSON.stringify(tools, null, 2)};\n`;

writeFileSync(outPath, header + body, "utf8");

console.log(`✓ ${tools.length} tools across ${categories.length} categories`);
console.log(`  written to ${path.relative(root, outPath)}`);
