/**
 * Import the install catalog (docs/install-catalog/justtuit-all-install-catalog.tsv)
 * into the manager model.
 *
 * Maps only the methods that correspond to an existing Managers field and whose
 * command shape is unambiguous (Homebrew, Cargo, Go, npm/Yarn, PyPI/pipx,
 * apt, dnf, pacman, winget). Anything else (source builds, release downloads,
 * official install scripts, Docker, Nix, Snap, AUR, apk, uv, ...) is left out on
 * purpose - no guessed identifiers.
 *
 * Run with:  bun scripts/import-catalog.ts
 * Output:    src/registry/catalog.ts (generated; do not edit by hand).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import type { Managers } from "../src/registry/types.js";

type Field = keyof Managers;

interface Parsed {
  field: Field;
  id: string;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const tsvPath = path.join(root, "docs", "install-catalog", "justtuit-all-install-catalog.tsv");
const outPath = path.join(root, "src", "registry", "catalog.ts");

function parseIdentifier(method: string, oneLiner: string): Parsed | null {
  // Normalize: strip a leading sudo and collapse whitespace.
  const c = oneLiner.trim().replace(/^sudo\s+/, "").replace(/\s+/g, " ");
  const m = method.trim();

  // First argument after the matched command that is not a flag (`-x` / `--x`)
  // and not an env assignment (`KEY=value`).
  const firstArg = (cmdRe: RegExp): string | undefined => {
    const after = c.replace(cmdRe, "");
    return after.split(/\s+/).find((t) => t !== "" && !t.startsWith("-") && !t.includes("="));
  };

  if (m === "Homebrew" || m === "Homebrew cask") {
    const tap = c.match(/brew\s+tap\s+([^\s&]+)/);
    const inst = c.match(/brew\s+install\s+(?:--cask\s+)?(\S+)/);
    if (inst) return { field: "brew", id: tap ? `${tap[1]!}/${inst[1]!}` : inst[1]! };
    return null;
  }
  if (m === "Cargo" || m === "source + Cargo" || m === "Cargo/source" || m === "Cargo/git") {
    const id = firstArg(/^cargo\s+install\s+/);
    return id ? { field: "cargo", id } : null;
  }
  if (m === "Go" || m === "source + Go" || m === "Go dependency") {
    const id = firstArg(/^go\s+(?:install|get)\s+/);
    return id ? { field: "go", id: id.replace(/@latest$/, "") } : null;
  }
  if (m === "npm" || m === "npm global") {
    const id = firstArg(/^npm\s+(?:install|i)\s+/);
    return id ? { field: "npm", id } : null;
  }
  if (m === "Yarn") {
    const id = firstArg(/^yarn\s+global\s+add\s+/);
    return id ? { field: "npm", id } : null;
  }
  if (
    m === "PyPI" || m === "pipx" || m === "source + pip" || m === "setup.py" ||
    m === "venv + PyPI" || m === "venv + editable install" || m === "PyPI wheel" ||
    m === "PyPI/git" || m === "PyPI + dependency" || m === "PyPI (current yewtube)"
  ) {
    const id = firstArg(/^(?:python3?\s+-m\s+)?(?:pip3?|pipx)\s+install\s+(?:-e\s+)?/);
    return id ? { field: "pip", id: id.replace(/\[.*\]$/, "") } : null;
  }
  if (m === "apt" || m === "Debian package") {
    const id = firstArg(/^apt(?:-get)?\s+install\s+/);
    return id ? { field: "apt", id } : null;
  }
  if (m === "DNF") {
    const id = firstArg(/^dnf\s+install\s+/);
    return id ? { field: "dnf", id } : null;
  }
  if (m === "pacman") {
    const id = firstArg(/^pacman\s+-S\s+/);
    return id ? { field: "pacman", id } : null;
  }
  if (m === "winget") {
    const id = firstArg(/^winget\s+install\s+/);
    return id ? { field: "winget", id } : null;
  }
  return null;
}

function normalize(name: string): string {
  return name.trim().toLowerCase();
}

const tsv = readFileSync(tsvPath, "utf8");
const lines = tsv.split("\n").slice(1); // skip header

const catalog: Record<string, Managers> = {};
let imported = 0;
let skipped = 0;
const skippedMethods = new Set<string>();

for (const line of lines) {
  if (!line.includes("\t")) continue;
  const cols = line.split("\t");
  // category, tool, status, first_official_method, one_liner, note
  const [category, tool, status, method, oneLiner] = cols;
  if (!tool || !status) continue;
  if (status !== "VERIFIED_ONE_LINER") continue;
  if (!oneLiner || oneLiner === "—" || oneLiner.trim() === "") continue;
  if (!method) continue;

  const parsed = parseIdentifier(method, oneLiner);
  if (!parsed) {
    skipped++;
    skippedMethods.add(method);
    continue;
  }

  const key = normalize(tool);
  // Don't clobber an existing (better) identifier from a later, more-specific row.
  const entry = catalog[key] ?? {};
  entry[parsed.field] = parsed.id;
  catalog[key] = entry;
  imported++;
}

const header = `// Auto-generated by scripts/import-catalog.ts. Do not edit by hand.
// Re-generate with:  bun scripts/import-catalog.ts
//
// Install identifiers backfilled from the install catalog (first-official-method
// extraction). Only methods that map cleanly onto an existing Managers field are
// imported; hand-curated entries in curated.ts take precedence.
import type { Managers } from "./types.js";

`;

const body = `export const catalog: Record<string, Managers> = ${JSON.stringify(catalog, null, 2)};\n`;

writeFileSync(outPath, header + body, "utf8");

console.log(`✓ imported ${imported} install identifiers across ${Object.keys(catalog).length} tools`);
console.log(`  skipped ${skipped} non-mappable methods: ${[...skippedMethods].sort().join(", ")}`);
